### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: Qwen/Qwen2-7B-Instruct
adapter_name_or_path: saves/qwen2-7b/lora/sft
template: qwen
trust_remote_code: true

### export
export_dir: output/qwen2-7b-factivity
export_size: 5
export_device: cpu
export_legacy_format: false
